name: oua_flutter_eight
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  cloud_firestore: ^4.15.9
  firebase_auth: ^4.17.9
  firebase_core: ^2.27.1
  firebase_storage: ^11.6.10
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  fluttertoast: ^8.2.4
  font_awesome_flutter: ^10.7.0
  image_picker: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/png/
    - assets/onboarding_images/
    - assets/lokasyon_detay_images/mardin/

fonts:
  - family: Poppins
    fonts:
      - asset: lib/assets/fonts/Poppins-Regular.ttf
      - asset: lib/assets/fonts/Poppins-Bold.ttf
        weight: 700
      - asset: lib/assets/fonts/Poppins-Medium.ttf
        weight: 400
